# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7d74e7052e74446a4b73fe5c25175342382bd009894eb2f1944b89c6470a164406e360288bd9d8816e8b4a8131179a1d4785720600a9e562bd71d60ea708dc

test:
  secret_key_base: b235bdd9d7c8a891439ce9267650f113de96b880f096191657d1acf52cf48638a5b292fcb8481ade23e0dc9c9e4f88481af3efd9267ab57daac83f9919916cda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
